//PORJECT LIST
let projectList = {
  "projects": [
    {"index":"unityrebrand",
     "name":"Unity Rebrand",
     "tags":["Motion Design"],
     "desc":"Unity Technologies is a real-time development platform that allows creators to build applications and immersive experiences.",
     "visible":true},

    {"index":"present",
     "name":"Present Magazine",
     "tags":["Motion Design"],
     "desc":"Animated case study created for Banque Nationale's biannual magazine 'Present' following the theme of movement.",
     "visible":true},

    {"index":"obsidian",
     "name":"Obsidian",
     "tags":["Motion Design / Interactive Installation"],
     "desc":"Obsidian is a cross-medium, user-generated interactive experience.",
     "visible":true},

     {"index":"pow",
      "name":"POW",
      "tags":["Motion Design"],
      "desc":"Kinetic typography and motion design within a promotional video for Protect Our Winters Canada (POW), a non-profit fighting climate change.",
      "visible":true},

     {"index":"tag",
      "name":"TAG Conference",
      "tags":["Motion Design"],
      "desc":"Motion teaser created for TAG, a Canadian annual conference about commerce in the digital age.",
      "visible":true},

     {"index":"twocities",
       "name":"Two Cities",
       "tags":["Publication / Film Photography"],
       "desc":"Two Cities is a miniature black and white film photo series capturing familiarities within unfamiliar environments.",
       "visible":true},

      {"index":"novarose",
      "name":"Nova Rose",
      "tags":["Branding / Photography"],
      "desc":"Photography, album cover, and promotional material for Montreal-based singer Nova Rose's song 'Just In Case'.",
      "visible":false},


      {"index":"motion",
      "name":"Motion Dailies",
      "tags":["Motion Design / Illustration"],
      "desc":"A series of personal motion experiments, exercises, and sketches.",
      "visible":true},

      {"index":"motion2",
      "name":"Illustration Dailies",
      "tags":["Motion Design / Illustration"],
      "desc":"A series of personal fashion/editorial inspired illustrations.",
      "visible":true},

      {"index":"artifice",
       "name":"Artifact/Artifice",
       "tags":["Publication / 3D"],
       "desc":"Artifact/Artifice is an afictional publication documenting abstractions of our current day plastic commodities.",
       "visible":true},

    {"index":"studioloco",
     "name":"Studio Loco",
     "tags":["Brand Identity"],
     "desc":"A refreshed and modernized logo and branding mockup for Studio Loco, a recording studio in Montreal.",
     "visible":true},

    {"index":"typeseries",
     "name":"Type Series",
     "tags":["3D / Typography"],
     "desc":"A personal 3D type series using tone-on-tone textures and contrasting forms.",
     "visible":true},

    {"index":"stepforward",
     "name":"Step Forward",
     "tags":["Exhibition Design"],
     "desc":"Graphic design vernissage poster and art direction for the graduating class of 2016 at Dawson College.",
     "visible":false},

     {"index":"pictureperfect",
      "name":"Picture Perfect",
      "tags":["Motion Design"],
      "desc":"Picture Perfect is a short motion piece that summarizes the evolution of the camera.",
      "visible":false},

      {"index":"logistec",
       "name":"Logistec",
       "tags":["Branding / Stationery"],
       "desc":"Brand stationery revamp and uniformization for Logistec Corporation, a stevedoring and terminal operator in eastern Canada.",
       "visible":false},

      {"index":"windsoftheworld",
       "name":"Winds of the World",
       "tags":["Web Design"],
       "desc":"<a href='https://hybrid.concordia.ca/v_ourdo/cart433/#'>Winds of the World</a> is an (in progress) interactive webGL application depicting global wind speeds, temperatures and weather through an abstract, minimalistic interface.",
       "visible":false},

     {"index":"flint",
      "name":"Flint Water Crisis",
      "tags":["Poster Design"],
      "desc":"A1 visual statement poster. Won a <a target='_blank' href='https://www.appliedartsmag.com/aace/'>Young & Student AACE Award</a> and was published in the 2016 student edition of <a target='_blank' href='https://appliedarts.ca/'>Applied Arts Magazine</a>.",
      "visible":false},

    {"index":"collectorsbox",
     "name":"Collector's Box",
     "tags":[" Packaging"],
     "desc":"A mock-up Daft Punk limited edition collector's box with four CDs and four lyrics books.",
     "visible":false},

    {"index":"printmanual",
     "name":"Print Manual",
     "tags":["Publication"],
     "desc":"A personal, original printed version of a research paper conducted on printing.",
     "visible":false},

    {"index":"programguide",
     "name":"Program Guide",
     "tags":["Publication / Illustration"],
     "desc":"An institutional booklet promoting the Graphic Design program at Dawson College, filled with tips and tricks for potential and current students and original illustrations.",
     "visible":false},

    {"index":"keepup",
     "name":"Keep Up",
     "tags":["Motion Design / Illustration"],
     "desc":"Keep Up< is a motion graphic commentary on how humans affect the environment due to the overconsumption of natural materials.",
     "visible":false},

    {"index":"eradise",
     "name":"Eradise",
     "tags":["Video Game Design / 3D"],
     "desc":"Eradise is an explorative third person mini-game made in Unity.",
     "visible":false},

    {"index":"lonebox",
     "name":"LoneBox",
     "tags":["Tangible Media"],
     "desc":"A lonely box that yearns for attention. Collaboration with <a target='_blank' href='http://www.miha-ko.ca/'>Codrin Tablan Negrei</a>.",
     "visible":false},

    {"index":"crookedcat",
     "name":"Crooked Cat",
     "tags":["Brand Identity / Illustration"],
     "desc":"An illustrative logo created for the fictional band 'Crooked Cats'.",
    "visible":false},

    {"index":"chroma",
     "name":"Chroma",
     "tags":["Tangible Media"],
     "desc":"<i>Chroma</i> is a wearable technology aimed towards performance artists. The dress uses an accelerometer and tension sensor to provide unique and instant light feedback (hue, saturation, value, and animated patterns) on the wearer’s left arm. Collaboration with <a target='_blank' href='http://www.miha-ko.ca/'>Codrin Tablan Negrei</a>.",
    "visible":false},

    {"index":"spring",
     "name":"Spring",
     "tags":["Motion Design"],
     "desc":"<i>Spring</i> follows a seed as it sprouts and blooms into a flower.",
    "visible":false},

    {"index":"kiriko",
     "name":"Kiriko",
     "tags":["Interactive Instillation"],
     "desc":"<i>Kiriko</i> is a user-based simulation and installation illustrating our relationship with the environment.",
     "visible":false},

    {"index":"digitalphotography",
     "name":"Bliss",
     "tags":["Digital Photography"],
     "desc":"A short photo series exploring blissful moments, the ephemeral, and anonymity.",
     "visible":true},

    {"index":"filmphotography",
     "name":"Ephemera",
     "tags":["Film Photography"],
     "desc":"A short photo series exploring light and translucency.",
     "visible":true},

     {"index":"2d3d",
      "name":"2D/3D Studio",
      "tags":["Experiments / Exercises"],
      "desc":"A series of personal 3D renders and illustrations.",
      "visible":false},

     {"index":"interactionstudio",
      "name":"Interaction Studio",
      "tags":["Experiments / Exercises"],
      "desc":"A series of personal experiments and exercises.",
      "visible":false},
  ]
}
